### ISSUE TITLE
401 token过期问题

### ISSUE THREAD

**Issue by shandian6033** [Prixii/auto_novel_reader_flutter#3]
![1730564382892](https://github.com/user-attachments/assets/86fef33b-867d-41e1-9635-3b8749a52f9d)

**Comment by Prixii** [comment]
重新登陆就可以了
大概率是我的 token 刷新逻辑出现疏漏了，最近超忙的（dev 分支已经鸽完了），看看能不能抽出时间修修

**Comment by shandian6033** [comment]
感谢大佬的火速修理
